import Head from "next/head";
import Home from "../Components/Home/Home";

const Index =() => {
  return (
    <>
      <Head>
        <title>Talkative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
}

export default Index;